# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stud/s3602940/Documents/game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stud/s3602940/Documents/game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stud/s3602940/Documents/game/CMakeFiles /home/stud/s3602940/Documents/game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stud/s3602940/Documents/game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named checker

# Build rule for target.
checker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 checker
.PHONY : checker

# fast build rule for target.
checker/fast:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/build
.PHONY : checker/fast

CannonBall.o: CannonBall.cpp.o

.PHONY : CannonBall.o

# target to build an object file
CannonBall.cpp.o:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/CannonBall.cpp.o
.PHONY : CannonBall.cpp.o

CannonBall.i: CannonBall.cpp.i

.PHONY : CannonBall.i

# target to preprocess a source file
CannonBall.cpp.i:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/CannonBall.cpp.i
.PHONY : CannonBall.cpp.i

CannonBall.s: CannonBall.cpp.s

.PHONY : CannonBall.s

# target to generate assembly for a file
CannonBall.cpp.s:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/CannonBall.cpp.s
.PHONY : CannonBall.cpp.s

Island.o: Island.cpp.o

.PHONY : Island.o

# target to build an object file
Island.cpp.o:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Island.cpp.o
.PHONY : Island.cpp.o

Island.i: Island.cpp.i

.PHONY : Island.i

# target to preprocess a source file
Island.cpp.i:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Island.cpp.i
.PHONY : Island.cpp.i

Island.s: Island.cpp.s

.PHONY : Island.s

# target to generate assembly for a file
Island.cpp.s:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Island.cpp.s
.PHONY : Island.cpp.s

Shield.o: Shield.cpp.o

.PHONY : Shield.o

# target to build an object file
Shield.cpp.o:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Shield.cpp.o
.PHONY : Shield.cpp.o

Shield.i: Shield.cpp.i

.PHONY : Shield.i

# target to preprocess a source file
Shield.cpp.i:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Shield.cpp.i
.PHONY : Shield.cpp.i

Shield.s: Shield.cpp.s

.PHONY : Shield.s

# target to generate assembly for a file
Shield.cpp.s:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Shield.cpp.s
.PHONY : Shield.cpp.s

Ship.o: Ship.cpp.o

.PHONY : Ship.o

# target to build an object file
Ship.cpp.o:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Ship.cpp.o
.PHONY : Ship.cpp.o

Ship.i: Ship.cpp.i

.PHONY : Ship.i

# target to preprocess a source file
Ship.cpp.i:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Ship.cpp.i
.PHONY : Ship.cpp.i

Ship.s: Ship.cpp.s

.PHONY : Ship.s

# target to generate assembly for a file
Ship.cpp.s:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Ship.cpp.s
.PHONY : Ship.cpp.s

Source.o: Source.cpp.o

.PHONY : Source.o

# target to build an object file
Source.cpp.o:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Source.cpp.o
.PHONY : Source.cpp.o

Source.i: Source.cpp.i

.PHONY : Source.i

# target to preprocess a source file
Source.cpp.i:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Source.cpp.i
.PHONY : Source.cpp.i

Source.s: Source.cpp.s

.PHONY : Source.s

# target to generate assembly for a file
Source.cpp.s:
	$(MAKE) -f CMakeFiles/checker.dir/build.make CMakeFiles/checker.dir/Source.cpp.s
.PHONY : Source.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... checker"
	@echo "... edit_cache"
	@echo "... CannonBall.o"
	@echo "... CannonBall.i"
	@echo "... CannonBall.s"
	@echo "... Island.o"
	@echo "... Island.i"
	@echo "... Island.s"
	@echo "... Shield.o"
	@echo "... Shield.i"
	@echo "... Shield.s"
	@echo "... Ship.o"
	@echo "... Ship.i"
	@echo "... Ship.s"
	@echo "... Source.o"
	@echo "... Source.i"
	@echo "... Source.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

